In [4]:
import pandas as pd
import plotly.express as px

In [3]:
energy_df = pd.read_csv("../data/energy/energy_dataset.csv")
energy_df.head()

,time,generation biomass,generation fossil brown coal/lignite,generation fossil coal-derived gas,generation fossil gas,generation fossil hard coal,generation fossil oil,generation fossil oil shale,generation fossil peat,generation geothermal,...,generation waste,generation wind offshore,generation wind onshore,forecast solar day ahead,forecast wind offshore eday ahead,forecast wind onshore day ahead,total load forecast,total load actual,price day ahead,price actual
0,2015-01-01 00:00:00+01:00,447.0,329.0,0.0,4844.0,4821.0,162.0,0.0,0.0,0.0,...,196.0,0.0,6378.0,17.0,NaN,6436.0,26118.0,25385.0,50.10,65.41
1,2015-01-01 01:00:00+01:00,449.0,328.0,0.0,5196.0,4755.0,158.0,0.0,0.0,0.0,...,195.0,0.0,5890.0,16.0,NaN,5856.0,24934.0,24382.0,48.10,64.92
2,2015-01-01 02:00:00+01:00,448.0,323.0,0.0,4857.0,4581.0,157.0,0.0,0.0,0.0,...,196.0,0.0,5461.0,8.0,NaN,5454.0,23515.0,22734.0,47.33,64.48
3,2015-01-01 03:00:00+01:00,438.0,254.0,0.0,4314.0,4131.0,160.0,0.0,0.0,0.0,...,191.0,0.0,5238.0,2.0,NaN,5151.0,22642.0,21286.0,42.27,59.32
4,2015-01-01 04:00:00+01:00,428.0,187.0,0.0,4130.0,3840.0,156.0,0.0,0.0,0.0,...,189.0,0.0,4935.0,9.0,NaN,4861.0,21785.0,20264.0,38.41,56.04

In [13]:
energy_df["time"] = pd.to_datetime(energy_df.time, utc=True)

In [15]:
energy_df.head()

,time,generation biomass,generation fossil brown coal/lignite,generation fossil coal-derived gas,generation fossil gas,generation fossil hard coal,generation fossil oil,generation fossil oil shale,generation fossil peat,generation geothermal,...,generation waste,generation wind offshore,generation wind onshore,forecast solar day ahead,forecast wind offshore eday ahead,forecast wind onshore day ahead,total load forecast,total load actual,price day ahead,price actual
0,2014-12-31 23:00:00+00:00,447.0,329.0,0.0,4844.0,4821.0,162.0,0.0,0.0,0.0,...,196.0,0.0,6378.0,17.0,NaN,6436.0,26118.0,25385.0,50.10,65.41
1,2015-01-01 00:00:00+00:00,449.0,328.0,0.0,5196.0,4755.0,158.0,0.0,0.0,0.0,...,195.0,0.0,5890.0,16.0,NaN,5856.0,24934.0,24382.0,48.10,64.92
2,2015-01-01 01:00:00+00:00,448.0,323.0,0.0,4857.0,4581.0,157.0,0.0,0.0,0.0,...,196.0,0.0,5461.0,8.0,NaN,5454.0,23515.0,22734.0,47.33,64.48
3,2015-01-01 02:00:00+00:00,438.0,254.0,0.0,4314.0,4131.0,160.0,0.0,0.0,0.0,...,191.0,0.0,5238.0,2.0,NaN,5151.0,22642.0,21286.0,42.27,59.32
4,2015-01-01 03:00:00+00:00,428.0,187.0,0.0,4130.0,3840.0,156.0,0.0,0.0,0.0,...,189.0,0.0,4935.0,9.0,NaN,4861.0,21785.0,20264.0,38.41,56.04

In [14]:
energy_df.dtypes

time                                           datetime64[ns, UTC]
generation biomass                                         float64
generation fossil brown coal/lignite                       float64
generation fossil coal-derived gas                         float64
generation fossil gas                                      float64
generation fossil hard coal                                float64
generation fossil oil                                      float64
generation fossil oil shale                                float64
generation fossil peat                                     float64
generation geothermal                                      float64
generation hydro pumped storage aggregated                 float64
generation hydro pumped storage consumption                float64
generation hydro run-of-river and poundage                 float64
generation hydro water reservoir                           float64
generation marine                                          float64
generation nuclear                                         float64
generation other                                           float64
generation other renewable                                 float64
generation solar                                           float64
generation waste                                           float64
generation wind offshore                                   float64
generation wind onshore                                    float64
forecast solar day ahead                                   float64
forecast wind offshore eday ahead                          float64
forecast wind onshore day ahead                            float64
total load forecast                                        float64
total load actual                                          float64
price day ahead                                            float64
price actual                                               float64
dtype: object

In [6]:
px.line(data_frame=energy_df, x="time", y="generation fossil gas")

In [7]:
px.line(data_frame=energy_df, x="time", y="total load actual")

In [20]:
month_df = energy_df.groupby(energy_df.time.dt.month).sum()
month_df.head()

,generation biomass,generation fossil brown coal/lignite,generation fossil coal-derived gas,generation fossil gas,generation fossil hard coal,generation fossil oil,generation fossil oil shale,generation fossil peat,generation geothermal,generation hydro pumped storage aggregated,...,generation waste,generation wind offshore,generation wind onshore,forecast solar day ahead,forecast wind offshore eday ahead,forecast wind onshore day ahead,total load forecast,total load actual,price day ahead,price actual
time,,,,,,,,,,,,,,,,,,,,,
1,1210958.0,1525517.0,0.0,16476797.0,14024210.0,895976.0,0.0,0.0,0.0,0.0,...,804393.0,0.0,18719549.0,3174792.0,0.0,18814958.0,88804490.0,88488571.0,153920.76,183423.21
2,1093910.0,1023031.0,0.0,13652721.0,10558666.0,816400.0,0.0,0.0,0.0,0.0,...,695361.0,0.0,17934342.0,3311627.0,0.0,17812658.0,80125731.0,79686101.0,122784.87,144563.30
3,1108152.0,653432.0,0.0,14300442.0,9187111.0,895545.0,0.0,0.0,0.0,0.0,...,739303.0,0.0,20125641.0,4076277.0,0.0,20117870.0,85166118.0,85180772.0,127545.77,142454.11
4,930534.0,834793.0,0.0,13764705.0,9308032.0,804448.0,0.0,0.0,0.0,0.0,...,751375.0,0.0,15736103.0,4235401.0,0.0,15705385.0,79579067.0,79324819.0,126970.95,139069.49
5,1125296.0,1013176.0,0.0,15028057.0,10676609.0,880178.0,0.0,0.0,0.0,0.0,...,726900.0,0.0,15974339.0,5205956.0,0.0,16068314.0,82414198.0,82236990.0,136293.32,154423.18

In [21]:
px.line(data_frame=month_df, x=month_df.index, y="total load actual")

In [30]:
px.pie(values=energy_df.describe().iloc[1], names=energy_df.describe().iloc[1].index)

In [45]:
mean_generation_values = energy_df.describe().iloc[1].sort_values(ascending=False)
mean_generation_values = mean_generation_values[mean_generation_values>0]
mean_generation_values = mean_generation_values[:-2]
other = pd.Series(mean_generation_values[7:].sum(), index=["other"])
mean_generation_values = mean_generation_values[:7].append(other)
mean_generation_values

/var/folders/8r/4jrrmbyd2hsbp5tjhv6zd1c00000gn/T/ipykernel_44730/4073590135.py:5: FutureWarning:

The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

total load forecast                28712.129962
total load actual                  28696.939905
generation nuclear                  6263.907039
generation fossil gas               5622.737488
forecast wind onshore day ahead     5471.216689
generation wind onshore             5464.479769
generation fossil hard coal         4256.065742
other                               8469.753803
dtype: float64

In [46]:
px.pie(values=mean_generation_values, names=mean_generation_values.index)